version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.7"

python:
  install:
    - requirements: 'docs/source/requirements.txt'

sphinx:
  configuration: 'docs/source/conf.py'
  fail_on_warning: true
