name: Bug/Crash report.
description: Create a bug report to help us improve our app.
labels:
  - "Bug"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report correctly.

  - type: textarea
    id: what
    attributes:
      label: What is the bug or the crash?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the issue
      description: |
        Steps, sample datasets to reproduce the behavior.
        Screencasts or screenshots are more than welcome, you can drag&drop them in the text box.

        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: about-info
    attributes:
      label: Versions
      description: |
        Which version is in use. Version can be find in VERSION file, in project root or from backoffice.
    validations:
      required: true


  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here.
