blank_issues_enabled: true

contact_links:
  - name: Documentation
    url: https://github.com/dbchiro/DjangoSinpOrganisms/
    about: Please read carefully the documentation before to submit an issue.
