#!/bin/bash


export BASE_DIR=$(dirname "${SCRIPT_DIR}")
export SETTINGS="${BASE_DIR}/install/settings.ini"
export LOG_FILE="${BASE_DIR}/install/install.log"


# Make sure root isnt running the script
if [ "$(id -u)" == "0" ]; then
    echo "This script must NOT be run as root" 1>&2
    exit 1
fi

echo $SETTINGS
if [ ! -f "${SETTINGS}" ]; then
    echo "Fichier de configuration '${SETTINGS}' non trouvé"
    echo "Avez-vous copié et adapté le fichier d’exemple ?"
    exit 1
fi
. "${SETTINGS}" || exit 1


function write_log() {
	echo -e $1
	echo "" &>> ${LOG_FILE}
	echo "" &>> ${LOG_FILE}
	echo "--------------------" &>> ${LOG_FILE}
	echo -e $1 &>> ${LOG_FILE}
	echo "--------------------" &>> ${LOG_FILE}
}
